// import { Inter } from 'next/font/google'
import './globals.css'
import Home from './page'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Workflow-Management',
  description: 'Generated by ',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main >
        {children}
        </main>
      </body>
    </html>
  )
}
